services:
  postgres:
    image: postgres:15-alpine
    container_name: meubanco_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-meudev}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-meudatabase}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: meubanco_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tickteira_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}?schema=public"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PAGFACIL_WEBHOOK_SECRET: ${PAGFACIL_WEBHOOK_SECRET}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tickteira_frontend
    restart: always
    ports:
      - '3001:3001'
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data: